import { AppBar, Container, Link, Toolbar, Typography } from '@material-ui/core'
import Head from 'next/head'
import NextLink from 'next/link'
import useStyles from '../utils/styles'

export default function Layout({ children }) {
    const classes = useStyles()
    return (
        <div>
            <Head>
                <title>Ecomercely</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppBar className={classes.navbar}>
                <Toolbar>
                    <NextLink href='/' >
                        <Typography className={classes.brand}>
                            ECOMERCELY
                        </Typography>
                    </NextLink>
                    <div className={classes.grow}></div>
                    <div>
                        <NextLink href="/cart">
                            CART
                        </NextLink>
                        <NextLink href="/login">
                            LOGIN
                        </NextLink>
                    </div>
                </Toolbar>
            </AppBar>
            <Container>
                {children}
            </Container>
        </div>
    )
}
