import { AppBar, Container, Toolbar, Typography } from '@material-ui/core'
import Head from 'next/head'
import useStyles from '../utils/styles'

export default function Layout({ children }) {
    const classes = useStyles()
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppBar className={classes.navbar}>
                <Toolbar>
                    <Typography>
                        Ecomercely
                    </Typography>
                </Toolbar>
            </AppBar>
            <Container>
                {children}
            </Container>
        </div>
    )
}
