import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <ul>
        <h1>Products</h1>
        <li>Prod 1</li>
        <li>Prod 2</li>
        <li>Prod 3</li>
      </ul>
    </div>
  )
}
